export const state = {
  rollDice: [],
  saveRolledDice: 0,
  playDiceCounter: [],
  playerPoints: 0,
  enemyDiceCounter: [],
  enemyPoints: 0,
  player1Points: 0,
  player2Points: 0,
  ship: false,
  captain: false,
  crew: false,
  selectedLootDice: false,
  currentRound: 0,
  gameRound: 1,
  mode: "",
};
